### ISSUE TITLE
Show usage with Pandas for historical hourly data

### ISSUE THREAD

**Issue by scheung38** [scls19fr/openweathermap_requests#5]
I do not see examples of using  Pandas to show historical hourly data? Thanks

**Comment by scls19fr** [comment]
`get_historic_weather` should returns a DataFrame
 but it is working only with some station_id (because of some limitations of OpenWeatherMap)


try in a web browser

http://api.openweathermap.org/data/2.5/history/station?type=hour&end=1422748799&start=1422662400&appid=YOURAPPID&id=5530

use http://www.onlineconversion.com/unix_time.htm for "end" and "start"

You will see that there is no data !! ("list" key)

You need to find first your nearest station

http://api.openweathermap.org/data/2.5/weather?appid=YOURAPPID&lat=YOURLAT&lon=YOURLON

if you don't find a station_id with historical data available through API I can't help you.

If you find an other website with data freely available I suggest you to use `requests`

http://www.python-requests.org/en/latest/
